module:
  block: 0
  breakpoint: 0
  dblog: 0
  dynamic_page_cache: 0
  field: 0
  filter: 0
  gin_toolbar: 0
  jsonapi: 0
  minimal: 0
  node: 0
  page_cache: 0
  path_alias: 0
  serialization: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
theme:
  claro: 0
  gin: 0
profile: minimal
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
